#!/usr/bin/env python

"""A tool to list currently available server images."""

import sys
import getopt

from RackSpaceManager import RackSpaceManager
from Exceptions import *

if __name__ == "__main__":

    manager = RackSpaceManager()

    try:
        images = manager.ListImages(isDetail = True)
    except RackSpaceException, e:
        print e
        sys.exit(2)

    for image in images:
        print "%6s %12s %8s %8s" % (image.id, image.name, image.status, image.progress)
