#!/usr/bin/env python

"""Reboot server."""

import sys
import getopt

from RackSpaceManager import RackSpaceManager
from Exceptions import *

def usage():
    print "Usage:\n%s -i serverId [-h]\n" % sys.argv[0]

if __name__ == "__main__":
    serverId = None
    hardReboot = False

    try:
        opts, args = getopt.getopt(sys.argv[1:], "i:h")
    except getopt.GetoptError, err:
        print str(err)
        sys.exit(2)

    for o, a in opts:
        if o == "-h":
            hardReboot = True
        elif o == "-i":
            serverId = a

    manager = RackSpaceManager()
    if serverId is None:
        usage()
        sys.exit(2)

    try:
        manager.RebootServer(serverId = serverId, hardReboot = hardReboot)
    except RackSpaceException:
        print "Error, cannot reboot specified server"
        sys.exit(2)

    print "Done."

